on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.17.0
      uses: actions/setup-node@v1
      with:
        node-version: 16.17.0
    - name: npm install
      run: npm install
    - name: lint
      run: npm run lint
